# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f48145314408ecabd93929a12eefc162db72c19858170e49677b9c215447ec3b1f576c687a01ebb9984c7c4648ee7399f72c027a0fcaff765e480866c5a5ce9

test:
  secret_key_base: 23c0e2d565ba47b1889b4ddfe2bdd5227cba2d6a79c75c5b33a125f785bdf9132a0f3cfec5749b1c871b4e0f474ee30ab3fcda10b3c061074aa7680ba64c8a7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
